#!/bin/bash

WAN_FIRSTPROJECT_API_CREDENTIAL=/Users/nebula/Desktop/'APIMyFirstProject-92c62bb05cb3.json'

WAN_NEBULACLOUD_ID=nebulacloud-197608
WAN_NEBULACLOUD_FALSE_ID=nebula-cloud-197510
WAN_FIRSTPROJECT_ID=studious-rhythm-197504

# StarCloud
K8S_GCP_CREDENTIAL=/Users/nebula/Desktop/StarCloud-95c31ad3f13a.json
StarCloud_ID=starcloud-200604

GCP_CREDENTIAL=${1:-${WAN_FIRSTPROJECT_API_CREDENTIAL}}
GCP_PROJECT=${2:-${WAN_FIRSTPROJECT_ID}}
CONTROLLER_NODES=${3:-1}
WORKER_GPU_NODES=${4:-0}
WORKER_CPU_NODES=${5:-2}
PASSWORD_PASSPHRASE=${6:-"123456"}

# ./first_bootstrap.sh | tee log.txt
./2_bootstrap.sh ${GCP_CREDENTIAL} ${GCP_PROJECT} ${CONTROLLER_NODES} ${WORKER_GPU_NODES} ${WORKER_CPU_NODES} ${PASSWORD_PASSPHRASE} | tee log.txt
